/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Cadence Demo
 * Test Event Bus
 * OpenAPI spec version: 1.0.0
 */

export interface Day {
  end: string;
  open: boolean;
  start: string;
}
