/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Cadence Demo
 * Test Event Bus
 * OpenAPI spec version: 1.0.0
 */
import type { LocationOpenDays } from "./locationOpenDays";

export interface Location {
  addressLine1: string;
  disabledAccess?: string;
  facia: string;
  id: string;
  openDays: LocationOpenDays;
  postCode: string;
  products: string[];
  town: string;
}
