/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Cadence Demo
 * Test Event Bus
 * OpenAPI spec version: 1.0.0
 */
import type { Day } from "./day";

export type LocationOpenDays = {
  monday: Day;
  tuesday: Day;
  wednesday: Day;
  thursday: Day;
  friday: Day;
  saturday: Day;
  sunday: Day;
};
