// Generated by parseopenapi version: 0ce237482a Mon Jun 5 17:17:17 2023 +0300
package repository

import (
	"errors"

	Openapi "github.com/davidsteed/cognito/api"
)

var ErrNotFound = errors.New("not found")

type Store struct {
	Repository
}

type Repository interface {
	Openapi.ServerInterface
}

func New() Repository {
	return &Store{}
}
